---
title: "F1 Project"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
    warning = F, message = F, tidy = TRUE, tidy.opts = list(width.cutoff = 60), 
    R.options = list(max.print = 100))
```

Brandon Deeb (btd543)



And away we go! Loading stuff up.

```{R}
library(tidyverse)
library(dplyr)
getwd()
races <- read.csv("races.csv")
qualifying <- read.csv("qualifying.csv")
results <- read.csv("results.csv")
lap_times <- read.csv("lap_times.csv")
driver_standings <- read.csv("driver_standings.csv")
constructor_standings <- read.csv("constructor_standings.csv")
constructor_results <- read.csv("constructor_results.csv")
drivers <- read.csv("drivers.csv")
constructors <- read.csv("constructors.csv")
status <- read.csv("status.csv")

```

In this portion, I am cleaning up data; removing anything prior to 2017 because I only started following F1 after watching a documentary about the 2017 season. Depending on what results show, I might go back and use all of the data to get more interesting results about a team/nationality's likelihood to win. 

```{R}
races %>% filter(year > 2016) -> races
qualifying %>% filter(raceId > 968) -> qualifying
results %>% filter(raceId > 968) -> results
lap_times %>% filter(raceId > 968) -> lap_times
driver_standings %>% filter(raceId > 968) -> driver_standings
constructor_standings %>% filter(raceId > 968) -> constructor_standings
constructor_results %>% filter(raceId > 968) -> constructor_results
```

Further cleaning, removing undesirable columns, such as Wikipedia pages and other information I won't need. This information has some really valuable information, all the way down to the times for qualifying races used to set grid order, but for some reason also has a lot of 'noise'. 

```{R}
drivers %>% select(driverId, driverRef, nationality) -> drivers
constructors %>% select(constructorId, name) -> constructors
races %>% select(raceId, name) -> races
```

Inital merging of datasets; getting all useful information into one clean table. This join adds the names of drivers to the dataset based on their Driver Id, so at a glance you can know who is who. 

```{R}
left_join(results, drivers, by="driverId") -> lol
```

This join adds the status of each racer to the results.  This was also originally just given as a number, but it's much easier to see that someone blew a tire than to track down what a 'Status 4' means in a race. 

```{R}
left_join(lol, status, by="statusId") -> lol
```

Similar to the Driver Id join, but this is for constructors, or the people who engineer the cars. Very important information to have for this dataset (SPOILER: after watching for a couple episodes, it was very apparent to see how money is such a big factor. Big companies like this literally shell out millions of dollars every year just to...have a slightly bigger advantage in car design? It's kind of biased and skews results, as other drivers literally never stand a chance, but interseting nonetheless).

```{R}
left_join(lol, constructors, by="constructorId") -> lol
lol %>% select(-driverId, -constructorId, -number, -position, -positionText, -fastestLap, -statusId) -> lol
```

Adding the locations/names of each Grand Prix instead of a numerical value. This will be useful in determining outliers in certain factors, seen later in the project. 

```{R}
left_join(lol, races, by="raceId") -> lol
lol %>% select(-rank) -> lol
lol %>% rename("team"=name.x)-> lol
lol %>% rename("grand prix"=name.y)-> lol
lol %>% rename("place"=positionOrder) -> lol
```

Untidying and Retidying. For some reason, this portion did not work. I balanced the parentheses like you suggested, but it still refused to re-tidy.  

```{R}
#lol %>% pivot_wider(names_from="team", values_from="points") -> untidy
#untidy %>% pivot_longer(cols=c("Ferrari", "Mercedes", "Red Bull", "Williams", "Force India", "Toro Rosso", "Renault", "Sauber", "McLaren", "Haas F1 Team", "Alfa Romeo", "Racing Point", "AlphaTauri"),names_to="team", values_to="points")
```

Exploring the dataset using dplyr functions!

This analysis is aimed at seeing who crashes the most! Initial analysis takes all those that crash and puts them in a separate table. Further analysis looks to compare how many of these people who crash tend to place (surprise, those who finish first, tend not to crash). 

```{R}
lol %>% filter(status=="Accident")-> crash
crash %>% group_by(driverRef) %>% summarize(count=n()) %>% arrange(-count)
lol %>% group_by(driverRef) %>% summarize(mean(place)) -> performance
performance %>% arrange(performance$`mean(place)`)
```

Looking at the fastest lap speed for drivers in each Grand Prix. For some reason, this wasn't numerical, so I made it numerical. I used the average fastest lap speed to break the dataset into the 'Really Fast' and the 'Kinda Fast' (a fun little jest; can't imagine a world where 209mph is only relatively fast! LOL I couldn't even imagine driving that fast on the highway!). Not that surprisingly, the fastest lap speeds consistently stay with Ferrari and Mercedes, two teams that spend astronomically more than the other competitors.  


```{R}
lol %>% arrange(desc(fastestLapSpeed))-> fast
fast %>% filter(fastestLapSpeed!="\\N")-> fast
fast %>% head()
fast$fastestLapSpeed <- as.numeric(as.character(fast$fastestLapSpeed))
fast %>% summarize(mean(fastestLapSpeed, na.rm=T))
fast %>% mutate(HowFast = case_when(fastestLapSpeed>=209 ~ "Really Fast", fastestLapSpeed<=209 ~ "Kinda Fast")) -> fast
fast %>% glimpse()
```

Using this same analysis to see if maybe there's a correlation between slow speeds and Grand Prix. Turns out, when there are slow speeds, there tend to be a lot of them! I was wondering why that could be, and a quick Google search answered all of my questions: the races that have lots of slow speeds tend to have tracks that have lots of curves, so there aren't as many chances to get a fast break and show off speed. I further examined the amount of times a driver shows up in this 'slow' category to confirm that it is the track; for the most part, those that race consistently have a similar appearance at this 'slow' speed (some of the higher ranking individuals do show up less, but not by much). 

```{R}
fast %>% summarize(quantile(fastestLapSpeed))
fast %>% filter(fastestLapSpeed < 198) -> slow
slow %>% glimpse()
slow %>% group_by(`grand prix`) %>% summarize(count=n()) %>% arrange(-count)
slow %>% ungroup() %>% group_by(driverRef) %>% summarize(count=n()) %>% arrange(-count) -> k
```


Statistics time!

Removing pesky NAs from data before finding the mean, sd, and percentiles for each numeric of interest. Grouping by various catergories to see who overall has a better performance (again, big surprise, but the champions tend to do much better in every aspect). Definitely my favorite analysis, nationality of driver! The Dutch and Finnish really seem to have a sort of knack for F1, as they outperform other nationalities by a pretty fair amount!

```{R}
lol %>% glimpse()
lol %>% filter(fastestLapSpeed!="\\N") -> stats
stats$fastestLapSpeed <- as.numeric(stats$fastestLapSpeed)
stats %>% na.omit()
stats %>% summarize_at(c("fastestLapSpeed", "laps", "points", "grid", "place"), mean, na.rm=T)
stats %>% summarize_at(c("fastestLapSpeed", "laps", "points", "grid", "place"), sd, na.rm=T)
stats %>% summarize_at(c("fastestLapSpeed", "laps", "points", "grid", "place"), quantile, na.rm=T)
stats %>% group_by(driverRef) %>% summarize_at(c("fastestLapSpeed", "laps", "points", "grid", "place"), mean, na.rm=T) %>% arrange(place)
stats %>% group_by(team) %>% summarize_at(c("fastestLapSpeed", "laps", "points", "grid", "place"), mean, na.rm=T) %>% arrange(place)
stats %>% group_by(nationality) %>% summarize_at(c("fastestLapSpeed", "laps", "points", "grid", "place"), mean, na.rm=T) %>% arrange(place) 
```


Visualizations


This is the heatmap showing the correlations between all of the numeric variables in the dataset (Fastest Lap Speed, Laps, Place, Starting Grid Position, and Points).  Unfortunately, a lot of these are directly related (i.e. drivers score points based on their placement, which tend to correspond to the amount of laps they drive).  Because of this, there are pretty strong correlations, but it wouldn't be measureing much to say "when drivers finish first, they get more points".  The interesting thing to note, and the one I really did want to test, was how starting grid position correlated with placement.  They trend positively, which makes sense (lower starting grid position means more likely to finish lower (still weird to conceptualize low being good)).  Grid position also trends negatively with Fastest Lap Speed.  As previously mentioned, the teams at the top tend to be superior at engineering, meaning their cars have a better performance, which often translates to better results.  Looking at the heat map, there is a negative correlation between Fastest Lap Speed and Place, as when a car tends to have a faster top speed, it tends to finish first, in a lower position.   

```{R}
lol %>% na.omit()
lol %>% summarize(cor(grid,place, use="pair"))
lol$fastestLapSpeed <- as.numeric(lol$fastestLapSpeed)
matrix <- lol %>% select(fastestLapSpeed, laps, points, grid, place) %>% cor(use="pair")
tidymatrix <-matrix %>% as.data.frame %>% rownames_to_column("var1") %>% pivot_longer(-1,names_to="var2", values_to="correlation")
tidymatrix
tidymatrix %>% ggplot(aes(var1,var2,fill=correlation))+geom_tile()+  scale_fill_gradient2(low="red",mid="white",high="blue")+geom_text(aes(label=round(correlation,2)))+  xlab("Var1")+ylab("Var2")+coord_fixed()
```

Comparing starting grid position to finishing placement. As per expectation, the general trend is that a better starting position results in a better finishing position (i.e. if you start ahead, their are less people to pass!). While comparably to each adjacent value, the difference is not astronomical, a drastic difference can be seen when the spread gets larger.  Teams that tend to start in the back half of the pack have a significantly harder time battling back to place well. While the colors might be a bit difficult to track, it also worth noting that there is a large congregation of winning teams in the bottom left by winning placements.  Very rarely (if at all) did a driver start in the very front of the grid and end up not placing well.  

```{R}
lol %>% filter(grid!=0) -> grid
library(RColorBrewer)
nb.cols <- 13
mycolors <- colorRampPalette(brewer.pal(8, "YlOrRd"))(nb.cols)
ggplot(grid,aes(x=grid,y=place))+geom_point(aes(color=team))+ geom_smooth() +ggtitle("Expected Placement by Grid Position")+ xlab("Starting Grid Position") + ylab("Finishing Placement") + theme_grey() +scale_color_manual(values=mycolors)

```

The most important comparison in F1: what teams on average finish best? Really interestingly, even the top contenders really have a large deviation.  While Ferrari and Red Bull give Mercedes a good challenge, their average placements are nearly double that of the champion.  Also intriguing is how much scrapping goes on amongst the remaining teams! Outside of the top three placing teams, there seem to be an initial five teams that fight to be the 'best of the rest', with the last five teams showing a somewhat weak fight. 

```{R}
lol %>% group_by(team) %>% summarize(mean(place)) -> placements
library(RColorBrewer)
nb.cols <- 13
mycolors <- colorRampPalette(brewer.pal(8, "Spectral"))(nb.cols)
placements %>% ggplot(aes(x=reorder(team, `mean(place)`),y=`mean(place)`,fill=team,),stat="summary",fun=mean)+ geom_col() + labs(title="Average Placement for Teams")+ scale_x_discrete(guide=guide_axis(n.dodge=3)) + xlab("Team") + ylab("Average Finishing Placement") + theme_dark() + scale_fill_manual(values= mycolors)
```


Clustering, here we GOOooo


In a sense, this measures how much 'influence' each variable has.  The PC values we obtain will be a measure of how much variance can be predicted from a particular pair of variables.  For instance, PC1 might be a measure of starting grid placement and finishing placement.  PC1 is then a vector that the eigenvector (a measure of the influence of both of these variables) points to.  

```{R}
library(cluster)
lol %>% filter(fastestLapSpeed!="\\N") %>% select(grid, place, fastestLapSpeed, points, laps) -> cluster
fit <- lol %>% select_if(is.numeric) %>% select(-resultId, -raceId) %>% scale
rownames(fit) <- lol$driverRef
f1_pca <- princomp(na.omit(fit))
names(f1_pca)
summary(f1_pca, loadings=T)
```

```{R}
eigval <- f1_pca$sdev^2
varprop = round(eigval/sum(eigval),2)
```
#ggplot() + geom_bar(aes(y=varprop, x=1:7), stat="identity") + xlab("") + geom_path(aes(y=varprop, x=1:7)) + 
  geom_text(aes(x=1:7, y=varprop, label=round(varprop, 2)), vjust=1, col="white", size=5) + 
  scale_y_continuous(breaks=seq(0, .6, .2), labels = scales::percent) + 
  scale_x_continuous(breaks=1:10)   
```{R}
round(cumsum(eigval)/sum(eigval), 2)
eigval                                                                                                     
summary(f1_pca, loadings=T)
f1df <-  data.frame(PC1=f1_pca$scores[, 1], PC2=f1_pca$scores[, 2])
ggplot(f1df, aes(PC1, PC2)) + geom_point()
```

This comparison shows the highest scoring on PC1 (which in racing, is actually the worst; high scores means finishing last). It then shows extremely low PC1 scorer, who are the top two drivers in F1 during this stint. Essentially, PC1 measures how well a driver performs in regards to the relationship between these two variables.   Similar results are shown for PC2, which compare Fastest Lap Speed and laps completed, and which are negatively correlated.  When filtering for highest scoring in PC1, we get drivers who typically do not perform well, as they start in high grid values and finish late.  For the lowest scoring PC1 values, we get drivers who are champions, like Hamilton and Vettel.  For PC2, we see the opposite trend.  

```{R}
f1_pca$scores[,1:4] %>% as.data.frame  %>% top_n(3, Comp.1)
f1_pca$scores[,1:4] %>% as.data.frame  %>% top_n(-3, Comp.1)
f1_pca$scores[,1:4] %>% as.data.frame  %>% top_n(3, wt=Comp.2)
f1_pca$scores[,1:4] %>% as.data.frame %>% top_n(3, wt=desc(Comp.2))

lol %>% filter(driverRef%in%c("hamilton","vettel","bottas"))
lol %>% filter(driverRef%in%c("kevin_magnussen","jolyon_palmer","brendon_hartley"))
```